// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycqcaxjzkennceeuxyrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcWNheGp6a2VubmNlZXV4eXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzYyMTksImV4cCI6MjA2NDA1MjIxOX0.GFfc-tYkdS6afKJgX9YUlYlZNTXZ5Q2z8OVWJQSGbNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);