// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twezspyyovvcemfeziif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZXpzcHl5b3Z2Y2VtZmV6aWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjYzODIsImV4cCI6MjA2NTAwMjM4Mn0.5Rv485X-LK9rLw6AfIGeM14elucKadRuU41VnyUIr-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);